LookingForGuild/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('frontdoor.urls')),
    url(r'^admin', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^guilds/', include('guilds.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

guilds/urls.py
from django.conf.urls import url
from .views import GuildList, CreateGuild, GuildDetail, RecruitmentPostDetail, CreateRecruitmentPost, UpdateGuildProfile, UpdateRecruitmentPost, DeleteGuild
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', GuildList.as_view(), name='guild-list'),
    url(r'^add_guild', login_required(CreateGuild), name='add-guild'),
    url(r'^guild_detail/(?P<guild_realm>[^/]+)/(?P<guild_name>[^/]+)', login_required(GuildDetail), name = 'guild-detail'),
    url(r'^add_recruitment_post/(?P<guild_pk>[^/]+)', login_required(CreateRecruitmentPost.as_view()), name='add-recruitment-post'),
    url(r'^recruitment_post/(?P<pk>[^/]+)', login_required(RecruitmentPostDetail.as_view()), name = 'recruitment-post'),
    url(r'^update_guild_profile/(?P<pk>[^/]+)', login_required(UpdateGuildProfile.as_view()), name='update-guild-profile'),
    url(r'^update_recruitment_post/(?P<pk>[^/]+)', login_required(UpdateRecruitmentPost.as_view()), name='update-recruitment-post'),
    url(r'^delete_guild/(?P<pk>[^/]+)', DeleteGuild, name='delete-guild'),
]

guilds/models.py
from django.db import models
from players.models import Realms, Factions, Classes, Factions
from django.contrib.auth.models import User, Group


class Guilds(models.Model):
    guild_name = models.CharField(max_length=255, null=False, blank=False)
    guild_realm = models.ForeignKey(Realms)
    guild_faction = models.ForeignKey(Factions)
    guild_created_by = models.ForeignKey(User)
    guild_information = models.TextField(null=True, blank=True)
    guild_battlenet_website = models.URLField(null=True, blank=True)
    guild_external_website = models.URLField(null=True, blank=True)
    guild_wow_progress_link = models.URLField(null=True, blank=True)
    guild_warcraft_logs_link = models.URLField(null=True, blank=True)
    guild_world_of_logs_link = models.URLField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_recruiting = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'guilds'
        verbose_name_plural = 'Player Guilds'
        ordering = ['guild_realm']
        unique_together = ('guild_name', 'guild_realm', 'guild_faction')
        
    def __str__(self):
        return self.guild_name


class GuildManagers(models.Model):
    guild_id = models.ForeignKey(Guilds, on_delete=models.CASCADE)
    guild_manager = models.ManyToManyField(User)

    class Meta:
        managed = True
        db_table = 'guild_managers'
        verbose_name_plural = 'Guild Managers'
        ordering =['guild_id']

    def __str__(self):
        return "%s - %s - %s" % (self.guild_id, self.guild_id.guild_realm.realm_name, self.guild_id.guild_faction.faction_name)


class RaidDays(models.Model):
    raid_day = models.CharField(max_length=10)

    class Meta:
        managed = True
        db_table = 'raid_days'
        verbose_name_plural = 'Raid Day Listing'

    def __str__(self):
        return self.raid_day


class RaidTimes(models.Model):
    time_value = models.TimeField()

    class Meta:
        managed = True
        db_table = 'raid_times'
        verbose_name_plural = 'Raid Time Listings'

    def __str__(self):
        return str(self.time_value)


class RecruitmentPosts(models.Model):
    guild_name = models.ForeignKey(Guilds)
    recruiting_levels = models.CharField(max_length=100)
    recruiting_classes = models.ManyToManyField(Classes)
    raid_days = models.ManyToManyField(RaidDays)
    raid_start_time = models.ForeignKey(RaidTimes, blank=True, null=True, related_name='RaidStartTime')
    raid_end_time = models.ForeignKey(RaidTimes, blank=True, null=True, related_name='RaidEndTime')
    recruitment_title = models.CharField(max_length=200)
    recruitment_post = models.TextField()
    is_post_active = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        managed = True
        db_table = 'recruitment_posts'
        verbose_name_plural = 'Recruitment Postings'

guilds/forms.py
from django import forms
from players.models import Realms


class CreateGuildForm(forms.Form):
    guild_name = forms.CharField(max_length=50)
    guild_realm = forms.ModelChoiceField(queryset=Realms.objects.all())
    

guilds/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views.generic import UpdateView
from .forms import CreateGuildForm
from .models import Guilds, RecruitmentPosts, GuildManagers
from players.models import Realms, Factions
from players.api_functions import get_guild_information
from django.views.generic import ListView, CreateView, DetailView


class GuildList(ListView):
    model = Guilds
    queryset = Guilds.objects.filter(is_recruiting=True, is_active=True)
    template_name = 'guilds/guilds.html'
    ordering = ['guild_realm', 'is_recruiting']
    grouping = ['guild_realm']


def GuildDetail(request, guild_realm, guild_name):
    context = {'guild_info': Guilds.objects.filter(guild_name = guild_name).filter(guild_realm = Realms.objects.get(realm_name = guild_realm))}
    return render(request, 'guilds/guild_details.html', context)

    
class RecruitmentPostDetail(DetailView):
    model = RecruitmentPosts
    template_name = 'guilds/recruitment_post_details.html'
    
    
def CreateGuild(request):
    form = CreateGuildForm()

    if request.method == 'POST':
        form = CreateGuildForm(data=request.POST)
        if form.is_valid():
            guild_information_from_api = get_guild_information(request.POST['guild_name'], request.POST['guild_realm'])

            new_guild, created = Guilds.objects.get_or_create(
                    guild_name = guild_information_from_api['guild_name'],
                    guild_realm = Realms.objects.get(id=guild_information_from_api['guild_realm']),
                    guild_faction = Factions.objects.get(faction_id = guild_information_from_api['guild_faction']),
                    guild_created_by = User.objects.get(id=request.user.id),
                    )
            new_guild_manager = GuildManagers.objects.create(guild_id = Guilds.objects.get(id = new_guild.id))
            new_guild_manager.guild_manager.add(request.user.id)

            return redirect('user-profile')
        else:

            return render(request, 'guilds/add_guild.html', {'form': form})
            
    else:
        return render(request, 'guilds/add_guild.html', {'form': form})


    fields = ['guild_name', 'guild_realm', 'guild_faction']
    #fields = ['guild_name', 'guild_realm', 'guild_faction', 'guild_information', 'guild_battlenet_website', 'guild_external_website', 'guild_wow_progress_link', 'guild_warcraft_logs_link', 'guild_world_of_logs_link', 'is_recruiting']
    success_url = '/players/profile'

    def form_valid(self, form):
        form.instance.guild_created_by = self.request.user
        return super(CreateGuild, self).form_valid(form)   
        
        
class CreateRecruitmentPost(CreateView):
    model = RecruitmentPosts
    template_name = 'guilds/add_recruitment_post.html'
    fields = 'recruiting_levels', 'recruiting_classes', 'recruitment_title', 'raid_days', 'raid_start_time', 'raid_end_time', 'recruitment_post', 'is_post_active'
    success_url = '/players/profile'
    
    def get_context_data(self, **kwargs):
        ctx = super(CreateRecruitmentPost, self).get_context_data(**kwargs)
        ctx['guild_object'] = Guilds.objects.get(pk=self.kwargs['guild_pk'])
        return ctx

    def form_valid(self, form):
        form.instance.guild_name_id = self.kwargs['guild_pk']
        return super(CreateRecruitmentPost, self).form_valid(form) 
        
    
class UpdateGuildProfile(UpdateView):
    model = Guilds
    template_name = 'guilds/update_guild_profile.html'
    fields = 'guild_information', 'guild_battlenet_website', 'guild_external_website', 'guild_wow_progress_link', 'guild_warcraft_logs_link', 'guild_world_of_logs_link', 'is_recruiting'
    success_url = '/players/profile'

    def get_context_data(self, **kwargs):
        ctx = super(UpdateGuildProfile, self).get_context_data(**kwargs)
        ctx['guild_profile_object'] = Guilds.objects.get(id=self.kwargs['pk'])
        return ctx


class UpdateRecruitmentPost(UpdateView):
    model = RecruitmentPosts
    template_name = 'guilds/update_recreuitment_post.html'
    fields = 'recruiting_levels', 'recruiting_classes', 'recruitment_title', 'recruitment_post', 'is_post_active'
    success_url = '/players/profile'

    def get_context_data(self, **kwargs):
        ctx = super(UpdateRecruitmentPost, self).get_context_data(**kwargs)
        ctx['recruitment_post_object'] = RecruitmentPosts.objects.select_related('guild_name').get(id=self.kwargs['pk'])
        return ctx


@login_required()
def DeleteGuild(request,pk):
    Guilds.objects.get(id=pk).delete()
    return redirect('/players/profile')

templates/guilds/add_guild.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
    Add a Guild - {{ user.username }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  {{ form_fail }}
  {{ form.errors }}
  <br>
  <div class="row">
    <div class="col-md-12">
      <form method="post">
        {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
{% endblock %}

templates/guilds/add_recruitment_post.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
    Add Recruitment Post - {{ guild_object.guild_name }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      Recruitment Post for: {{ guild_object.guild_name }} - {{ guild_object.guild_realm }} - {{ guild_object.guild_faction }}
      <form method="post">
        {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
{% endblock %}

templates/guilds/guild_details.html
{% extends '_layout.html' %}

{% block title %}
Details for {% for guild_info in guild_info %} {{ guild_info.guild_name }} {% endfor %}
{% endblock %}

{% block content %}
{% for guild_info in guild_info %}
    Delete this guild => <a href="{% url 'delete-guild' guild_info.id %}">Delete {{ guild_info.guild_name }} - {{ guild_info.guild_realm }} - {{ guild_info.guild_faction }}</a><= This happens immediately.
    <br>
    <a href="{% url 'update-guild-profile' guild_info.id %}">Update Guild Details</a>
    <br>
    {{ guild_info.guild_name }}
    <br>
    {{ guild_info.guild_realm }}
    <br>
    {{ guild_info.guild_faction }}
    <br>
    {{ guild_info.guild_created_by }}
    <br>
    {{ guild_info.guild_information }}
    <br>
    {{ guild_info.guild_battlenet_website }}
    <br>
    {{ guild_info.guild_external_website }}
    <br>
    {{ guild_info.guild_wow_progress_link }}
    <br>
    {{ guild_info.guild_warcraft_logs_link }}
    <br>
    {{ guild_info.guild_world_of_logs_link }}
    <br>
    {{ guild_info.create_date }}
    <br>
    {{ guild_info.last_updated }}
    <br>
    Active Guild: {{ guild_info.is_active }}
    <br>
    Recruiting: {{ guild_info.is_recruiting }}
    <br>
    Recruitment Posts:
        {% for rcp in guild_info.recruitmentposts_set.all %}
            {% if rcp.is_post_active %}
                <p><a href="{% url 'recruitment-post' rcp.pk %}">{{ rcp.recruitment_title }}</a></p>
            {% else %}
                <p>Not recruiting at this time.</p>
            {% endif %}
        {% endfor %}
{% endfor %}
{% endblock %}

templates/guilds/guilds.html
{% extends '_layout.html' %}

{% block title %}
Guilds
{% endblock %}

{% block content %}

{% regroup object_list by guild_realm as realm %}
    {% for guild_realm in realm %}
        <h1>{{ guild_realm.grouper }}</h1>
        {% for guild in guild_realm.list %}
            {% if guild.is_recruiting %}
                <p><a href="{% url 'guild-detail' guild.pk %}">{{ guild.guild_name }}</a></p>
            {% endif %}
        {% endfor %}
    {% endfor %}

{% endblock %}

templates/guilds/recruitment_post_details.html
{% extends '_layout.html' %}

{% block title %}
Details for {{ object.recruitment_title }}
{% endblock %}

{% block content %}
    <a href="{% url 'update-recruitment-post' object.id %}">Update Recruitment Post</a>
    <br>
    <a href="{% url 'guild-detail' object.guild_name.pk %}">{{ object.guild_name }}</a>
    <br>
    {{ object.guild_faction }}
    <br>
    {{ object.recruiting_levels }}
    <br>
    Recruiting Classes: {% for x in object.recruiting_classes.all %} {{ x }} {% endfor %}
    <br>
    {{ object.recruitment_title }}
    <br>
    {{ object.recruitment_post }}
    <br>
    {{ object.is_post_active }}

{% endblock %}

templates/guilds/update_guild_profile.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
    Update Guild Profile - {{ guild_profile_object.guild_name }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      Updating: {{ guild_profile_object.guild_name }} - {{ guild_profile_object.guild_realm }}
      <form method="post">
        {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
{% endblock %}

templates/guilds/update_recreuitment_post.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
    Update Recruitment Post - {{ recruitment_post_object.guild_name }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      Updating: {{ recruitment_post_object.recruitment_title }}
      <form method="post">
        {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
{% endblock %}