LookingForGuild/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('frontdoor.urls')),
    url(r'^admin', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^guilds/', include('guilds.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

guilds/urls.py
from django.conf.urls import url
from .views import GuildList, CreateGuild, GuildDetail, RecruitmentPostDetail, CreateRecruitmentPost, UpdateGuildProfile, UpdateRecruitmentPost, DeleteGuild
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', GuildList.as_view(), name='guild-list'),
    url(r'^add_guild', login_required(CreateGuild), name='add-guild'),
    url(r'^guild_detail/(?P<guild_realm>[^/]+)/(?P<guild_name>[^/]+)', login_required(GuildDetail), name = 'guild-detail'),
    url(r'^add_recruitment_post/(?P<guild_pk>[^/]+)', login_required(CreateRecruitmentPost.as_view()), name='add-recruitment-post'),
    url(r'^recruitment_post/(?P<pk>[^/]+)', login_required(RecruitmentPostDetail.as_view()), name = 'recruitment-post'),
    url(r'^update_guild_profile/(?P<pk>[^/]+)', login_required(UpdateGuildProfile.as_view()), name='update-guild-profile'),
    url(r'^update_recruitment_post/(?P<pk>[^/]+)', login_required(UpdateRecruitmentPost.as_view()), name='update-recruitment-post'),
    url(r'^delete_guild/(?P<pk>[^/]+)', DeleteGuild, name='delete-guild'),
]

players/urls.py
from django.conf.urls import url
from .views import MyProfile, CreateCharacter, CharacterDetail, UpdateCharacterProfile
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^add_character', login_required(CreateCharacter), name='add-character'),
    url(r'^profile/', login_required(MyProfile), name='user-profile'),
    url(r'^character_details/(?P<character_realm>[^/]+)/(?P<character_name>[^/]+)', CharacterDetail, name='character-details'),
    url(r'^update_character_details/(?P<pk>[^/]+)', login_required(UpdateCharacterProfile.as_view()), name='update-character-details'),
]

players/models.py
from __future__ import unicode_literals
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


ROLES = (
    ('MELEE_DPS', 'Melee DPS'),
    ('RANGED_DPS', 'Ranged DPS'),
    ('TANK', 'Tank'),
    ('HEALER', 'Healer'),
    ('NO_ROLE_SELECTED', 'No Role Selected'),
)


class Timezones(models.Model):
    short_name = models.CharField(max_length=10, null=False, blank=False)
    full_name = models.CharField(max_length=100, null=False, blank=False)

    class Meta:
        managed = True
        db_table = 'timezones'
        verbose_name_plural = 'Timezone Listings'

    def __str__(self):
        return "%s - %s" % (self.short_name, self.full_name)


class Factions(models.Model):
    faction_id = models.IntegerField(null=False, blank=False, primary_key=True, unique=True)
    faction_name = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'factions'
        verbose_name_plural = 'Character Factions'

    def __str__(self):
        return self.faction_name


class Classes(models.Model):
        class_name = models.CharField(max_length=50)
        blizzard_class_id = models.IntegerField()
    
        class Meta:
            managed = True
            db_table = 'classes'
            verbose_name_plural = 'Character Classes'
            ordering = ['class_name']

        def __str__(self):
            return self.class_name


class Races(models.Model):
    race_id = models.IntegerField(null=False, blank=False, primary_key=True, unique=True)
    race_name = models.CharField(max_length=50)
    race_faction = models.ForeignKey(Factions, to_field='faction_id')

    class Meta:
        managed = True
        db_table = 'races'
        verbose_name_plural = 'Character Races'

    def __str__(self):
        return self.race_name


class Realms(models.Model):
    realm_type = models.CharField(max_length=50)
    realm_population = models.CharField(max_length=10)
    realm_name = models.CharField(max_length=50)
    realm_slug = AutoSlugField(populate_from='realm_name')
    realm_battlegroup = models.CharField(max_length=50)
    realm_locale = models.CharField(max_length=50)
    realm_timezone = models.CharField(max_length=255)
    realm_connected_realms = models.TextField()
    load_date = models.DateField()

    class Meta:
        managed = True
        db_table = 'realms'
        verbose_name_plural = 'Realms'
        ordering = ['realm_name']

    def __str__(self):
        return self.realm_name


class Regions(models.Model):
    region_name = models.CharField(max_length=3, null=False, blank=False)

    class Meta:
        managed = True
        db_table = 'regions'
        verbose_name_plural = 'Regions'
        ordering = ['region_name']

    def __str__(self):
        return self.region_name.upper()


#@receiver(post_save, sender=User)
#def create_user_profile(sender, instance, created, **kwargs):
#    if created:
#        Profile.objects.create(user=instance)


class Characters(models.Model):
    character_owner = models.ForeignKey(User)
    character_name = models.CharField(max_length=255)
    character_realm = models.ForeignKey(Realms)
    character_faction = models.ForeignKey(Factions)
    character_class = models.ForeignKey(Classes)
    character_race = models.ForeignKey(Races)
    character_level = models.IntegerField()
    equipped_ilevel = models.IntegerField()
    max_ilevel = models.IntegerField()
    main_role = models.CharField(max_length=30, choices=ROLES, default="NO_ROLE_SELECTED", null=True, blank=True)
    alt_role = models.CharField(max_length=30, choices=ROLES, default="NO_ROLE_SELECTED", null=True, blank=True)
    looking_for_guild = models.BooleanField(default=False)
    looking_for_guild_advertisement = models.TextField(null=True, blank=True)
    character_armory_url_simple = models.URLField(null=True, blank=True)
    character_armory_url_advanced = models.URLField(null=True, blank=True)
    character_profile_image_url = models.CharField(max_length=100, null=True, blank=True)
    character_profile_avatar_url = models.CharField(max_length=100, null=True, blank=True)
    character_profile_inset_url = models.CharField(max_length=100, null=True, blank=True)
    is_character_active = models.BooleanField(default=True)
    insert_date = models.DateField(auto_now_add=True)

    class Meta:
        managed = True
        db_table = 'characters'
        verbose_name_plural = 'Characters'
        unique_together = ('character_owner', 'character_name', 'character_realm')

    def __str__(self):
        return "%s of %s" % (self.character_name, self.character_realm)

    def create_character_slug(self):
        return "%s-%s-%s" % (
            self.character_name.lower(),
            self.character_realm.realm_name.lower().replace(' ', '-'),
            self.character_faction.faction_name.lower()
        )

players/forms.py
from django import forms

players/views.py
from players.api_functions import get_full_character_information, get_oauth_character_names
from .models import Realms, Characters, Factions, Classes, Races
from guilds.models import RecruitmentPosts, Guilds
from frontdoor.models import WebsiteAPISettings
from django.views.generic import UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialToken
from django.db import IntegrityError


def MyProfile(request):
    character_filters = {'character_owner_id': request.user.id, 'is_character_active': True}
    context = {
        'my_guilds': Guilds.objects.filter(guild_created_by=request.user),
        'my_recruitment_posts': RecruitmentPosts.objects.select_related('guild_name').filter(guild_name__guild_created_by=request.user),
        'my_characters': Characters.objects.filter(**character_filters).order_by('character_realm', '-character_level', 'character_name'),
        'website_settings': WebsiteAPISettings.objects.get(pk=1),
    }
    return render(request, 'players/profile.html', context)


def CharacterDetail(request, character_realm, character_name):
#def CharacterDetail(request, pk):
    context = {
        'site_settings': WebsiteAPISettings.objects.all().get(),
        'character_info': Characters.objects.filter(character_name = character_name).filter(character_realm = Realms.objects.get(realm_name = character_realm))
        #'character_info': Characters.objects.get(pk=pk)
    }
    return render(request, 'players/character_detail.html', context)


def CreateCharacter(request):
    # Flow
    # User clicks Add/Update my characters.
    # Pull Token
    AccessToken = SocialToken.objects.filter(account__user=request.user.id, account__provider='battlenet').get()
    # Get all characters from api build a list from the api of character|realm
    full_character_list_from_api = get_oauth_character_names(AccessToken.token)
    # Get list of characters/realms from DB, compare to list from api, delete from db what isn't in api
    my_db_toons = Characters.objects.filter(character_owner_id=request.user.id).values('character_name', 'character_realm__realm_name')
    toons_list = []
    for x in my_db_toons:
        toons_list.append( (x['character_name'], x['character_realm__realm_name']) )
    differences = [x for x in toons_list if x not in full_character_list_from_api]
    # Take the items in differences, and delete them from the db.
    for item in differences:
        Characters.objects.filter(character_owner_id=request.user.id).filter(character_name=item[0]).filter(character_realm__realm_name=item[1]).delete()
    # Done with the deletion stage.
    
    # Loop through full character list. 
    # Insert records for new characters that are in the api pull that aren't in the db
    # If a character is already in the db but has an updated level, race, or ilevel, update them.
    for toon_name, toon_realm in full_character_list_from_api:
        character_info = get_full_character_information(toon_name, toon_realm)
        try:
            new_character, created = Characters.objects.update_or_create(
                    character_owner_id = request.user.id,
                    character_name = character_info['character_name'].title(),
                    character_realm = Realms.objects.get(realm_name = character_info['character_realm']),
                    character_faction = Factions.objects.get(faction_id = character_info['character_faction']),
                    character_class = Classes.objects.get(blizzard_class_id = character_info['class_id']),
                    character_race = Races.objects.get(race_id = character_info['race_id']), 
                    character_level = character_info['level'], 
                    equipped_ilevel = character_info['equipped_ilevel'],
                    max_ilevel = character_info['max_ilevel'],
                    character_armory_url_simple = character_info['armory_simple'], 
                    character_armory_url_advanced = character_info['armory_advanced'], 
                    character_profile_image_url = character_info['profile_image'], 
                    character_profile_avatar_url = character_info['avatar_image'], 
                    character_profile_inset_url = character_info['inset_image'], 
                    defaults = {
                        'character_level': character_info['level'], 
                        'character_race': Races.objects.get(race_id = character_info['race_id']),
                        'equipped_ilevel': character_info['equipped_ilevel'],
                        'max_ilevel': character_info['max_ilevel'],
                        }
                    )
        except IntegrityError:
            Characters.objects.filter(
                    character_owner_id = request.user.id, 
                    character_name = character_info['character_name'], 
                    character_realm = Realms.objects.get(realm_name = character_info['character_realm'])
                    ).update(
                            character_level = character_info['level'],
                            character_race = Races.objects.get(race_id = character_info['race_id']),
                            equipped_ilevel = character_info['equipped_ilevel'],
                            max_ilevel = character_info['max_ilevel'],
                            )

    # Leave old characters for users to deactivate
    # Get all toons for this player
    #account_characters = Characters.objects.filter(character_owner = request.user)
    return redirect('user-profile')


class UpdateCharacterProfile(UpdateView):
    model = Characters
    template_name = 'players/update_character_profile.html'
    fields = 'looking_for_guild', 'looking_for_guild_advertisement', 'main_role', 'alt_role', 'is_character_active'
    success_url = '/players/profile'

    def get_context_data(self, **kwargs):
        ctx = super(UpdateCharacterProfile, self).get_context_data(**kwargs)
        ctx['character_profile_object'] = Characters.objects.get(id=self.kwargs['pk'])
        return ctx

templates/players/character_detail.html
{% extends '_layout.html' %}
{% block title %}
Character Details - {% for character_info in character_info %} {{ character_info.character_name }} {% endfor %}
{% endblock %}

{% block content %}
{% for character_info in character_info %}
<table class="table" background="{{ site_settings.wow_api_character_image_base_url }}{{ character_info.character_profile_image_url }}" background-repeat="no-repeat">
    <tr>
        <th>Name</th>
        <td>{{ character_info.character_name }}</td>
    </tr>
    <tr>
        <th>Class</th>
        <td>{{ character_info.character_class }}</td>
    </tr>
    <tr>
        <th>iLevel Equipped / iLevel Max</th>
        <td>{{ character_info.equipped_ilevel }} / {{character_info.max_ilevel }}</td>
    </tr>
    <tr>
        <th>Race</th>
        <td>{{ character_info.character_race }}</td>
    </tr>
    <tr>
        <th>Level</th>
        <td>{{ character_info.character_level }}</td>
    </tr>
    <tr>
        <th>Faction</th>
        <td>{{ character_info.character_faction }}</td>
    </tr>
    <tr>
        <th>Main Spec</th>
        <td>{{ character_info.get_main_role_display }}</td>
    </tr>
    <tr>
        <th>Off Spec</th>
        <td>{{ character_info.get_alt_role_display }}</td>
    </tr>
    <tr>
        <th>Armory (simple)</th>
        <td><a href="{{ character_info.character_armory_url_simple }}" target="_blank">Link</a></td>
    </tr>
    <tr>
        <th>Armory (advanced)</th>
        <td><a href="{{ character_info.character_armory_url_advanced }}" target="_blank">Link</a></td>
    </tr>
</table>
{% if character_info.looking_for_guild %}
<table class="table">
    <tr>
        <th>Looking For Guild Advertisement</th>
    </tr>
    <tr>
        <td>{% if character_info.looking_for_guild_advertisement == "" %}No advertisement notes.{% else %}{{ character_info.looking_for_guild_advertisement }}{% endif %}</td>
    </tr>
</table>
{% else %}
    Not currently looking for a guild.
{% endif %}

{% if character_info.character_owner.id == request.user.id  %}
    <p>Update {{ character_info.character_name }}'s Profile <a href="{% url 'update-character-details' character_info.id %}">Here!</a></p>
{% endif %}
{% endfor %}
{% endblock %}

templates/players/profile.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
My Profile - {{ user.username }}
{% endblock %}

{% block content %}

    <!--- Show Guilds I Own --->
    <h2>My Guilds</h2>

    <h4><a href="{% url 'add-guild' %}">Add a new Guild</a></h4>
    {% if my_guilds %}
        <table class="table">
            <tr>
                <th></th>
                <th>Name</th>
                <th>Realm</th>
                <th>Faction</th>
                <th>Add Recruitment Posts</th>
            </tr>
            {% for guild in my_guilds %}
                <tr>
                    <td><a href="{% url 'update-guild-profile' guild.id %}">Update Guild Information</a></td>
                    <td><a href="{% url 'guild-detail' guild.guild_realm guild.guild_name %}">{{ guild.guild_name }}</a></td>
                    <td>{{ guild.guild_realm }}</td>
                    <td>{{ guild.guild_faction }}</td>
                    <td><a href="{% url 'add-recruitment-post' guild_pk=guild.id %}">Here</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        You are not the owner of any guilds.
    {% endif %}

    <h2>My Recruitment Posts</h2>

    {% if my_recruitment_posts %}
        <table class="table">
            <tr>
                <th>Guild Name</th>
                <th>Post Title</th>
                <th>Created</th>
                <th>Active</th>
            </tr>
            {% for item in my_recruitment_posts %}
                <tr>
                    <td><a href="{% url 'update-recruitment-post' item.pk %}">{{ item.guild_name }}</a></td>
                    <td>{{ item.recruitment_title }}</td>
                    <td>{{ item.create_date|naturaltime }}</td>
                    <td>{{ item.is_post_active }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        You currently have no recruitment posts for any guilds you own.
    {% endif %}

    <!--- Show Characters I've Created --->
    <h2>My Characters</h2>

    <h4><a href="{% url 'add-character' %}">Add or Update My Characters</a></h4>
    <small>This will delete any characters you no longer have on your account.</small>

    <table class="table">
        <tr>
            <th></th>
            <th>Name</th>
            <th>Realm</th>
            <th>Faction</th>
            <th>Class</th>
            <th>Level</th>
            <th>iLevel Equipped / iLevel Max</th>
        </tr>
        {% for character in my_characters %}
            <tr>
                <td><img src="{{ website_settings.wow_api_character_image_base_url }}/{{ character.character_profile_inset_url }}"></td>
                <td><a href="{% url 'character-details' character.character_realm character.character_name %}">{{ character.character_name }}</a></td>
                <td>{{ character.character_realm }}</td>
                <td>{{ character.character_faction}}</td>
                <td>{{ character.character_class }}</td>
                <td>{{ character.character_level }}</td>
                <td>{{ character.equipped_ilevel }} / {{ character.max_ilevel }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/players/update_character_profile.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
    Update Character Profile - {{ character_profile_object.character_name }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      Updating: {{ character_profile_object.character_name }} - {{ character_profile_object.character_realm }}
      <form method="post">
        {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
{% endblock %}

templates/players/update_profile.html
{% extends '_layout.html' %}
{% load humanize %}

{% block title %}
    Update Profile - {{ user.username }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
      {% for user in user_object %}{{ user }}{% endfor %}
      <form method="post">
        {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
{% endblock %}